<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Table for PPDB Online Registrations (Pendaftaran Santri Baru)
        Schema::create('registrations', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('boarding_school_id')->constrained()->cascadeOnDelete();
            $table->foreignId('school_year_id')->constrained()->cascadeOnDelete();
            $table->string('registration_number')->unique(); // No. Pendaftaran
            $table->string('name');
            $table->string('nisn')->nullable();
            $table->string('gender');
            $table->string('place_of_birth');
            $table->date('date_of_birth');
            $table->text('address');
            $table->string('father_name')->nullable();
            $table->string('father_phone')->nullable();
            $table->string('mother_name')->nullable();
            $table->string('mother_phone')->nullable();
            $table->string('previous_school')->nullable();
            $table->decimal('registration_fee', 15, 2)->default(0);
            $table->enum('status', ['pending', 'verified', 'accepted', 'rejected'])->default('pending');
            $table->text('notes')->nullable();
            $table->string('payment_proof')->nullable(); // Bukti Transfer
            $table->timestamps();
        });

        // Table for Letter Templates (Surat Menyurat)
        Schema::create('letter_templates', function (Blueprint $table) {
            $table->id();
            $table->foreignUuid('boarding_school_id')->constrained()->cascadeOnDelete();
            $table->string('name'); // e.g., Surat Izin Pulang
            $table->string('code')->nullable(); // e.g., SIP
            $table->text('content'); // HTML content with placeholders
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });

        // Table for Generated Letters History
        Schema::create('letters', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('boarding_school_id')->constrained()->cascadeOnDelete();
            $table->foreignId('template_id')->constrained('letter_templates')->cascadeOnDelete();
            $table->foreignUuid('student_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('user_id')->constrained(); // Created/Generated by
            $table->string('letter_number')->unique();
            $table->date('date');
            $table->json('data')->nullable(); // Dynamic data used in template
            $table->string('file_path')->nullable(); // PDF path if saved
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('letters');
        Schema::dropIfExists('letter_templates');
        Schema::dropIfExists('registrations');
    }
};
